### ISSUE TITLE
Resource leak in loops

### ISSUE THREAD

**Issue by sekruse** [rheem-ecosystem/rheem#34]
There seems to be a resource leak associated with loops: Rheem uses a reference counting scheme to manage its resources, in particular persisted `ChannelInstance`s. Now, if a `ChannelInstance` inside of a loop is propagated to a subsequent loop iteration (because it is needed in the next iteration or because it tells whether to stop the loop), then it seems that there is a `ExecutionStageLoopIterationContext`s that obtains a reference to the `ChannelInstance` without releasing it.

**Comment by luckyasser** [comment]
@Muhaeb That probably explains your memory leak problem ?

**Comment by sekruse** [comment]
I think, I found the bug. We use "transition" contexts in between two iterations. It seems that we have not been declaring the erasure of the transition contexts properly to the reference counting facility. Thus, all "transition" channel instances were not swept, either.

@Muhaeb It would be great to hear if that eliminates or at least reduces said memory leak problem.

**Comment by Muhaeb** [comment]
So is it fixed now, can i sync and test?

**Comment by sekruse** [comment]
I have a fix, but I need to run the tests first and merge the fix if it passes. I will close this issue as soon as I am done with this.

**Comment by sekruse** [comment]
Okay, it's merged to the `master`.

**Comment by Muhaeb** [comment]
Lovely, thanks a million for spotting that and providing the fix.
