### ISSUE TITLE
SparkShufflePartitionSampleOperator may choose same partitions

### ISSUE THREAD

**Issue by zkaoudi** [rheem-ecosystem/rheem#8]
Currently the operator takes at random one partition and reads it sequentially in case it is used inside a loop. In case it reaches the end, it takes again a random one from all the partitions. This means that it may pick a partition that was already picked before. It's better to ensure that it will take a different one so that the entire data can be sampled eventually.

**Comment by sekruse** [comment]
Is that a bug, though? Or rather an enhancement? It's not violating any specification after all. :wink:

**Comment by zkaoudi** [comment]
Yes, I totally agree that is not exactly a bug. Just was playing with the various labels :P I will change it to enhancement 👍
