### ISSUE TITLE
How to "Contact us" 

### ISSUE THREAD

**Issue by NKcqx** [rheem-ecosystem/rheem#83]
Sorry in this way
For some reasons I just can't use "Contact Us" in http://da.qcri.org/rheem/contact/ , and denied by sending email directly to your email address.
I want to get some help of "Where is Rheem Studio and how to use it" and "Some guidence of import a new platform into rheem"
here is the original email:
" Hi, I'm now working on Cross-Platform Compute and I'm impressed by the powerful of Rheem. I want to present it to my BOSS but I can't find the tool of Visualization of Rheem Plan called Rheem Studio, can you tell me how to use it plz ?
And I'm trying to import a new platform into rheem but doesn't going well, maybe I havn't well understand it. It will be really helpful if you can give me some little guidence ~  Appreciate ~!"

**Comment by zkaoudi** [comment]
Hi, 
thank you for your message. Rheem Studio is not publicly available. @JorgeQuiane will contact you regarding that.

Regarding plugging a new platform these are the main steps you need to follow:
- Add execution operators with their mappings to Rheem operators. You may have to add new Rheem operators as well. See for example: 
[SparkFilterOperator.java](https://github.com/rheem-ecosystem/rheem/blob/master/rheem-platforms/rheem-spark/src/main/java/org/qcri/rheem/spark/operators/SparkFilterOperator.java)
[FilterMapping.java](https://github.com/rheem-ecosystem/rheem/blob/master/rheem-platforms/rheem-spark/src/main/java/org/qcri/rheem/spark/mapping/FilterMapping.java)

- Add an executor that is able to take these execution operators and compose a single job to submit it to the underlying platform. See for example:
[SparkExecutor.java](rheem/rheem-platforms/rheem-spark/src/main/java/org/qcri/rheem/spark/execution/SparkExecutor.java)

- Add communication channels to define the input-output of your execution operators and conversion operators between different types of channels. See for example: 
[RddChannel.java](https://github.com/rheem-ecosystem/rheem/blob/master/rheem-platforms/rheem-spark/src/main/java/org/qcri/rheem/spark/channels/RddChannel.java)
[ChannelConversions.java](https://github.com/rheem-ecosystem/rheem/blob/master/rheem-platforms/rheem-spark/src/main/java/org/qcri/rheem/spark/channels/ChannelConversions.java)

I hope this helps. Please let us know if you have further questions.

**Comment by NKcqx** [comment]
Thank you very much for the quickly reply! 
You can contact me via nkucqx@gmail.com. 
The guidence is very clear, I'll give a try, thank you for that again.
