### ISSUE TITLE
How you use JavaStream to preserve data in DAG

### ISSUE THREAD

**Issue by NKcqx** [rheem-ecosystem/rheem#84]
Hi, I'm encounting a problem which I don't have a nice plan to solve it. So I want to ask you with humble~
In Java Platform, when one operator have more than one successor to consume its data (e.g. branch in dag),  how you pass data sealed in `Stream` to multi successors since one `Stream` cannot be operated twice ?

Thanks

**Comment by NKcqx** [comment]
Or "Who put the result from `OutputSlot` into `InputSlot`.  Sorry to bother.

**Comment by berttty** [comment]
Hi @NKcqx  sorry for the later replay but I didn't see your issue, I don't know if you solve it or not, If you didn't I want to ask you for more information, like the code that you where trying to execute, to get more information and helping you in the best way.

Also you can join to the Rheem Slack(rheem-community.slack.com) or write and email to oss@rheem.io
